### ISSUE TITLE
Error adding entities for domain select with platform victron

### ISSUE THREAD

**Issue by Next9999** [sfstar/hass-victron#29]
On a restart....

tks for your work

Logger: homeassistant.components.select
Source: custom_components/victron/select.py:127
Integration: Select (documentation, issues)
First occurred: 9:38:37 PM (2 occurrences)
Last logged: 9:38:37 PM

Error adding entities for domain select with platform victron
Error while setting up victron platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 709, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 804, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 562, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 97, in state
    if self.current_option is None or self.current_option not in self.options:
  File "/config/custom_components/victron/select.py", line 127, in current_option
    return  self.description.options(self.description.value_fn(self.coordinator.processed_data(), self.description.slave, self.description.key)).name
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 0 is not a valid ess_mode

**Comment by sfstar** [comment]
Thank you for reporting.
This issue is the same (although the error is different due to at which stage the errors occurs) as the issue mentioned in #44
Therefore I will close this issue and continue investigation / troubleshooting in #44
