### ISSUE TITLE
Various warnings and errors in logs: value errors, type errors, and deprecated attributes

### ISSUE THREAD

**Issue by randyoo** [sfstar/hass-victron#74]
Upon updating to v0.1.0 release, after removing and re-adding the integration, my Home Assistant instance completely froze. While checking logs to try learn what caused the crash, I came across numerous warnings and errors relating to this integration.

Several of them specifically state that they should be reported to the custom integration author. Apologies if my reporting approach is less than ideal. It's not clear if some of these errors/warning should be grouped or split into separate issues.

I should also point out that that's possible that some of these are associated with brief/intermittent network connectivity between the HA server and GX device.

Log snippets follow:

`This error originated from a custom integration.

Logger: custom_components.victron.coordinator
Source: custom_components/victron/coordinator.py:76
Integration: victron (documentation, issues)
First occurred: May 9, 2023 at 6:56:04 PM (72 occurrences)
Last logged: 3:55:31 PM

no valid data returned for entities of slave: 100 if device was physically removed please force a rescan to resolve this issue
no valid data returned for entities of slave: 238 if device was physically removed please force a rescan to resolve this issue
no valid data returned for entities of slave: 237 if device was physically removed please force a rescan to resolve this issue
no valid data returned for entities of slave: 239 if device was physically removed please force a rescan to resolve this issue`

`Logger: homeassistant.helpers.entity
Source: helpers/entity.py:572
First occurred: May 9, 2023 at 11:20:14 PM (14 occurrences)
Last logged: 3:50:18 PM

Updating state for sensor.victron_battery_history_lastdischarge_239 (<class 'custom_components.victron.sensor.VictronSensor'>) took 0.430 seconds. Please report it to the custom integration author.
Updating state for sensor.victron_vebus_battery_voltage_237 (<class 'custom_components.victron.sensor.VictronSensor'>) took 1.721 seconds. Please report it to the custom integration author.
Updating state for sensor.victron_battery_alarm_lowsoc_239 (<class 'custom_components.victron.sensor.VictronSensor'>) took 1.881 seconds. Please report it to the custom integration author.
Updating state for sensor.victron_battery_alarm_239 (<class 'custom_components.victron.sensor.VictronSensor'>) took 1.947 seconds. Please report it to the custom integration author.
Updating state for sensor.victron_system_pvonoutput_l1 (<class 'custom_components.victron.sensor.VictronSensor'>) took 1.776 seconds. Please report it to the custom integration author.`

`This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/victron/sensor.py:155
Integration: victron (documentation, issues)
First occurred: May 10, 2023 at 12:50:23 AM (74 occurrences)
Last logged: 3:02:03 PM

Update for sensor.victron_battery_alarm_internalfailure_239 fails
Update for sensor.victron_battery_alarm_highchargetemperature_239 fails
Update for sensor.victron_battery_alarm_lowchargetemperature_239 fails
Update for sensor.victron_battery_alarm_lowcellvoltage_239 fails
Update for sensor.victron_system_battery_state fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 554, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
    await coro
  File "/config/custom_components/victron/sensor.py", line 155, in async_update
    self._attr_native_value = self.entity_type.decodeEnum(data).name.split("_DUPLICATE")[0]
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: None is not a valid register_input_source
`

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/victron/number.py:202
Integration: victron (documentation, issues)
First occurred: May 9, 2023 at 10:35:37 PM (12 occurrences)
Last logged: 2:27:36 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 852, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 366, in state
    return self.value
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 419, in value
    if (native_value := self.native_value) is None:
  File "/config/custom_components/victron/number.py", line 202, in native_value
    if value > round(UINT16_MAX/2): #Half of the UINT16 is reserved for positive and half for negative values
TypeError: '>' not supported between instances of 'NoneType' and 'int'
`
`This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/victron/base.py:10
Integration: victron (documentation, issues)
First occurred: May 10, 2023 at 12:50:26 AM (141 occurrences)
Last logged: 12:57:20 PM

Update for sensor.victron_battery_diagnostics_lasterror_2_time_239 fails
Update for sensor.victron_battery_diagnostics_lasterror_3_time_239 fails
Update for sensor.victron_battery_diagnostics_lasterror_4_time_239 fails
Update for sensor.victron_battery_system_mincelltemperature_239 fails
Update for sensor.victron_battery_system_maxcelltemperature_239 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 554, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
    await coro
  File "/config/custom_components/victron/sensor.py", line 153, in async_update
    data = self.description.value_fn(self.coordinator.processed_data(), self.description.slave, self.description.key)
  File "/config/custom_components/victron/base.py", line 10, in <lambda>
    value_fn: Callable[[dict], StateType] = lambda data, slave, key: data["data"][str(slave) + "." + str(key)]
KeyError: '100.settings_ess_batterylife_soclimit'
`

`This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/victron/number.py:202
Integration: victron (documentation, issues)
First occurred: 1:15:32 PM (1 occurrences)
Last logged: 1:15:32 PM

Error executing service: <ServiceCall number.set_value (c:01H060CM0KW5EJ4PRB3RN3RWGF): value=7094.0, entity_id=['number.victron_settings_ess_acpowersetpoint']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1867, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1889, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 815, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 366, in state
    return self.value
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 419, in value
    if (native_value := self.native_value) is None:
  File "/config/custom_components/victron/number.py", line 202, in native_value
    if value > round(UINT16_MAX/2): #Half of the UINT16 is reserved for positive and half for negative values
TypeError: '>' not supported between instances of 'NoneType' and 'int'
`

`Logger: homeassistant.helpers.service
Source: helpers/service.py:757
First occurred: May 9, 2023 at 5:39:15 PM (406 occurrences)
Last logged: 1:16:17 PM

Unable to find referenced entities number.victron_settings_ess_acpowersetpoint or it is/they are currently not available`

`Logger: homeassistant.components.number
Source: components/number/__init__.py:159
Integration: Number (documentation, issues)
First occurred: May 9, 2023 at 6:14:11 PM (187 occurrences)
Last logged: 1:16:17 PM

custom_components.victron.number is setting deprecated attributes on an instance of NumberEntityDescription, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.`

**Comment by randyoo** [comment]
Since reporting this issue, I've hard-wired my RPi running Venus OS (acting as a Cerbo). I've also confirmed that my Home Assistant server isn't overloaded, and still encountered the following warning:

`WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.victron_system_charger_power (<class 'custom_components.victron.sensor.VictronSensor'>) took 1.824 seconds. Please report it to the custom integration author.`

Just thought you should know that this particular warning might **not** be related to stability of the connection.
